export const COUNTRY_CODES = [
  { code: 'AF', dial: '+93', name: 'Afghanistan', flag: '🇦🇫', search: 'afghanistan af +93' },
  { code: 'AL', dial: '+355', name: 'Albania', flag: '🇦🇱', search: 'albania al +355' },
  { code: 'DZ', dial: '+213', name: 'Algeria', flag: '🇩🇿', search: 'algeria dz +213' },
  { code: 'AD', dial: '+376', name: 'Andorra', flag: '🇦🇩', search: 'andorra ad +376' },
  { code: 'AO', dial: '+244', name: 'Angola', flag: '🇦🇴', search: 'angola ao +244' },
  { code: 'AR', dial: '+54', name: 'Argentina', flag: '🇦🇷', search: 'argentina ar +54' },
  { code: 'AM', dial: '+374', name: 'Armenia', flag: '🇦🇲', search: 'armenia am +374' },
  { code: 'AU', dial: '+61', name: 'Australia', flag: '🇦🇺', search: 'australia au +61' },
  { code: 'AT', dial: '+43', name: 'Austria', flag: '🇦🇹', search: 'austria at +43' },
  { code: 'AZ', dial: '+994', name: 'Azerbaijan', flag: '🇦🇿', search: 'azerbaijan az +994' },
  { code: 'BH', dial: '+973', name: 'Bahrain', flag: '🇧🇭', search: 'bahrain bh +973' },
  { code: 'BD', dial: '+880', name: 'Bangladesh', flag: '🇧🇩', search: 'bangladesh bd +880' },
  { code: 'BE', dial: '+32', name: 'Belgium', flag: '🇧🇪', search: 'belgium be +32' },
  { code: 'BR', dial: '+55', name: 'Brazil', flag: '🇧🇷', search: 'brazil br +55' },
  { code: 'BG', dial: '+359', name: 'Bulgaria', flag: '🇧🇬', search: 'bulgaria bg +359' },
  { code: 'CA', dial: '+1', name: 'Canada', flag: '🇨🇦', search: 'canada ca +1' },
  { code: 'CN', dial: '+86', name: 'China', flag: '🇨🇳', search: 'china cn +86' },
  { code: 'CO', dial: '+57', name: 'Colombia', flag: '🇨🇴', search: 'colombia co +57' },
  { code: 'HR', dial: '+385', name: 'Croatia', flag: '🇭🇷', search: 'croatia hr +385' },
  { code: 'CY', dial: '+357', name: 'Cyprus', flag: '🇨🇾', search: 'cyprus cy +357' },
  { code: 'CZ', dial: '+420', name: 'Czech Republic', flag: '🇨🇿', search: 'czech republic cz +420' },
  { code: 'DK', dial: '+45', name: 'Denmark', flag: '🇩🇰', search: 'denmark dk +45' },
  { code: 'EG', dial: '+20', name: 'Egypt', flag: '🇪🇬', search: 'egypt eg +20' },
  { code: 'EE', dial: '+372', name: 'Estonia', flag: '🇪🇪', search: 'estonia ee +372' },
  { code: 'FI', dial: '+358', name: 'Finland', flag: '🇫🇮', search: 'finland fi +358' },
  { code: 'FR', dial: '+33', name: 'France', flag: '🇫🇷', search: 'france fr +33' },
  { code: 'DE', dial: '+49', name: 'Germany', flag: '🇩🇪', search: 'germany de +49' },
  { code: 'GH', dial: '+233', name: 'Ghana', flag: '🇬🇭', search: 'ghana gh +233' },
  { code: 'GR', dial: '+30', name: 'Greece', flag: '🇬🇷', search: 'greece gr +30' },
  { code: 'HK', dial: '+852', name: 'Hong Kong', flag: '🇭🇰', search: 'hong kong hk +852' },
  { code: 'HU', dial: '+36', name: 'Hungary', flag: '🇭🇺', search: 'hungary hu +36' },
  { code: 'IN', dial: '+91', name: 'India', flag: '🇮🇳', search: 'india in +91' },
  { code: 'ID', dial: '+62', name: 'Indonesia', flag: '🇮🇩', search: 'indonesia id +62' },
  { code: 'IE', dial: '+353', name: 'Ireland', flag: '🇮🇪', search: 'ireland ie +353' },
  { code: 'IL', dial: '+972', name: 'Israel', flag: '🇮🇱', search: 'israel il +972' },
  { code: 'IT', dial: '+39', name: 'Italy', flag: '🇮🇹', search: 'italy it +39' },
  { code: 'JP', dial: '+81', name: 'Japan', flag: '🇯🇵', search: 'japan jp +81' },
  { code: 'KE', dial: '+254', name: 'Kenya', flag: '🇰🇪', search: 'kenya ke +254' },
  { code: 'KR', dial: '+82', name: 'South Korea', flag: '🇰🇷', search: 'south korea kr +82 korea' },
  { code: 'KW', dial: '+965', name: 'Kuwait', flag: '🇰🇼', search: 'kuwait kw +965' },
  { code: 'MY', dial: '+60', name: 'Malaysia', flag: '🇲🇾', search: 'malaysia my +60' },
  { code: 'MX', dial: '+52', name: 'Mexico', flag: '🇲🇽', search: 'mexico mx +52' },
  { code: 'NL', dial: '+31', name: 'Netherlands', flag: '🇳🇱', search: 'netherlands nl +31 holland' },
  { code: 'NG', dial: '+234', name: 'Nigeria', flag: '🇳🇬', search: 'nigeria ng +234' },
  { code: 'NO', dial: '+47', name: 'Norway', flag: '🇳🇴', search: 'norway no +47' },
  { code: 'OM', dial: '+968', name: 'Oman', flag: '🇴🇲', search: 'oman om +968' },
  { code: 'PK', dial: '+92', name: 'Pakistan', flag: '🇵🇰', search: 'pakistan pk +92' },
  { code: 'PH', dial: '+63', name: 'Philippines', flag: '🇵🇭', search: 'philippines ph +63' },
  { code: 'PL', dial: '+48', name: 'Poland', flag: '🇵🇱', search: 'poland pl +48' },
  { code: 'PT', dial: '+351', name: 'Portugal', flag: '🇵🇹', search: 'portugal pt +351' },
  { code: 'QA', dial: '+974', name: 'Qatar', flag: '🇶🇦', search: 'qatar qa +974' },
  { code: 'RO', dial: '+40', name: 'Romania', flag: '🇷🇴', search: 'romania ro +40' },
  { code: 'RU', dial: '+7', name: 'Russia', flag: '🇷🇺', search: 'russia ru +7' },
  { code: 'SA', dial: '+966', name: 'Saudi Arabia', flag: '🇸🇦', search: 'saudi arabia sa +966' },
  { code: 'SG', dial: '+65', name: 'Singapore', flag: '🇸🇬', search: 'singapore sg +65' },
  { code: 'ZA', dial: '+27', name: 'South Africa', flag: '🇿🇦', search: 'south africa za +27' },
  { code: 'ES', dial: '+34', name: 'Spain', flag: '🇪🇸', search: 'spain es +34' },
  { code: 'LK', dial: '+94', name: 'Sri Lanka', flag: '🇱🇰', search: 'sri lanka lk +94' },
  { code: 'SE', dial: '+46', name: 'Sweden', flag: '🇸🇪', search: 'sweden se +46' },
  { code: 'CH', dial: '+41', name: 'Switzerland', flag: '🇨🇭', search: 'switzerland ch +41' },
  { code: 'TH', dial: '+66', name: 'Thailand', flag: '🇹🇭', search: 'thailand th +66' },
  { code: 'TR', dial: '+90', name: 'Turkey', flag: '🇹🇷', search: 'turkey tr +90' },
  { code: 'AE', dial: '+971', name: 'United Arab Emirates', flag: '🇦🇪', search: 'united arab emirates uae ae +971' },
  { code: 'GB', dial: '+44', name: 'United Kingdom', flag: '🇬🇧', search: 'united kingdom uk gb +44 britain' },
  { code: 'US', dial: '+1', name: 'United States', flag: '🇺🇸', search: 'united states usa us +1 america' },
  { code: 'VN', dial: '+84', name: 'Vietnam', flag: '🇻🇳', search: 'vietnam vn +84' },
  { code: 'ZM', dial: '+260', name: 'Zambia', flag: '🇿🇲', search: 'zambia zm +260' },
] as const
